repos:
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0
    hooks:
      - id: pre-commit-update
        args: [--dry-run]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^app/infrastructure/migrations/
      - id: end-of-file-fixer
        exclude: ^app/infrastructure/migrations/
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: '25.12.0'
    hooks:
      - id: black
        exclude: ^app/infrastructure/migrations/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.9
    hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      exclude: ^app/infrastructure/migrations/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.19.1'
    hooks:
      - id: mypy
        args: [--config-file, mypy.ini, .]
        types: [python]
        pass_filenames: false
        exclude: ^app/infrastructure/migrations/
